version: '3'

services: 
    backend:
        build: 
            context: .
            dockerfile: Dockerfile
        ports: 
            - 8001:5000
        volumes:
            - .:/app
        depends_on: 
            - db

    db:
        image: postgres
        environment: 
            - POSTGRES_PASSWORD=pets
        ports: 
            - "5432:5432"
        volumes: 
            - /var/lib/postgresql/data
