"""Fix name of table pets

Revision ID: 7d6bf0c7c573
Revises: 8ed6a2bcf403
Create Date: 2021-08-05 01:00:36.808730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d6bf0c7c573'
down_revision = '8ed6a2bcf403'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_pet', sa.String(length=250), nullable=True),
    sa.Column('pet_owner_name', sa.String(length=250), nullable=True),
    sa.Column('breed', sa.String(length=250), nullable=True),
    sa.Column('birth_date', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('pet')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pet',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name_pet', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('pet_owner_name', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('breed', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('birth_date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pet_pkey')
    )
    op.drop_table('pets')
    # ### end Alembic commands ###
