"""Create pets table

Revision ID: 8ed6a2bcf403
Revises: 
Create Date: 2021-08-04 20:30:55.436924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ed6a2bcf403'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_pet', sa.String(length=250), nullable=True),
    sa.Column('pet_owner_name', sa.String(length=250), nullable=True),
    sa.Column('breed', sa.String(length=250), nullable=True),
    sa.Column('birth_date', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pet')
    # ### end Alembic commands ###
