"""Add pet photo field in Pets model

Revision ID: ff36453c4c77
Revises: 7d6bf0c7c573
Create Date: 2021-08-05 20:46:44.620948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff36453c4c77'
down_revision = '7d6bf0c7c573'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('pet_photo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pets', 'pet_photo')
    # ### end Alembic commands ###
